In [3]:
# # # PyTorch asoslari
#  * PyTorch overview (NIma va qayerda ishlatiladi)
#  * Tensor tushunchasi
#    * Tensor yaratish usullari (torch.tensor , torch.zeros , torch.ones, torch.rand)
#    * Tensor shape,  o'lchamlari (view, reshape)
#    * Indexing, slicing, concatenation
#    * GPU (CUDA) va CPUda ishlatish
#  * Tensor va Numpy bilan ishlash (convert qilish)



In [4]:
# Tensor tushunchasi:
# Tensor bu ko'p o'lchamli massiv (multi-dimensional array)
# 0D tensor = skalyar (5)
# 1D Tensor = vektor ([1,2,3])
# 2D Tensor = matrix ([[1,2],[3,4]])
# 3D+ Tensor Ko'p o'lchamli massiv (masalan, rasmlar uchun [batch, channel, height  , width])

# PYtorch tensor GPU da ishlay oladi, bu juda katta farq Numpy dan


# Tensor 
import torch

In [5]:
import torch

print("PyTorch versiyasi:", torch.__version__)
print("CUDA mavjudmi?:", torch.cuda.is_available())
# Agar CUDA bo'lsa True bo'ladi aks holda False qayatadi

x = torch.tensor([1,2,3,4])
x

PyTorch versiyasi: 2.8.0+cpu
CUDA mavjudmi?: False


tensor([1, 2, 3, 4])

In [6]:
# Oddiy tensor yaraatish
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [7]:
# Float tipida tensor yaratish
b = torch.tensor([[1.0,2.0] , [3.0,4.0]] , dtype=torch.float32)
b

tensor([[1., 2.],
        [3., 4.]])

In [8]:
# Nol bilan to'ldirish
c = torch.zeros(2,3)
c

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
# Birlar bilan tensor yaratish
d = torch.ones(2,3)
d

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
# Random sonlar bilan yaratish
e =  torch.rand(3,3)
e

tensor([[0.9246, 0.4089, 0.3209],
        [0.1063, 0.1889, 0.2747],
        [0.4623, 0.0361, 0.9351]])

In [11]:
# Butun sonli random
f = torch.randint(0,10 ,(2,3))
f

tensor([[4, 6, 5],
        [8, 9, 4]])

Tensor shape, o'lchamlar

In [12]:
x = torch.rand(2,3)
x.shape # shape bu ustun va qatorlar sonini qaytaradi


torch.Size([2, 3])

In [13]:
# Rashape qilish
y = x.reshape(3,2)
y.shape

torch.Size([3, 2])

In [ ]:
z = x.view(-1,6)
z.shape

torch.Size([1, 6])

Indexing, slicing, concatenation

In [ ]:
# Indexing
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x[0,0] # 1-element (1)
x[1,:] # 2-qatordagi barcha elementlar [4,5,6]
x[:, 2] #  3-ustundagi barcha elemenlar [7,8,9]


tensor([3, 6, 9])

In [16]:
# Concatenation ikkita tensroni birlashtish
a = torch.ones(2,2)
b = torch.zeros(3,2)
cat = torch.cat((a,b), dim=0) # Qator bo'yicha
cat

tensor([[1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

GPU (CUDA) va CPUda ishlatish

In [17]:
# PyTorch GPU ni avtomatik ishlata oladi

# Qurilmani tanlash
device = torch.device("cuda"  if torch.cuda.is_available() else "cpu")

print("Ishlatilayotgan device" , device)

Ishlatilayotgan device cpu


In [18]:
# tensorni GPU o'tkazish
x = torch.rand(2,2).to(device)
x

tensor([[0.7810, 0.3484],
        [0.8414, 0.8398]])

Tensor va numpy bilan ishlash

In [19]:
# Tensor -> Numpy konvertatsiya qilish juda oson

import numpy as np

# Tensor -> Numpy

t = torch.ones(3)
n = t.numpy()
print("Tensor: " , t)
print("Numpy: " , n)


Tensor:  tensor([1., 1., 1.])
Numpy:  [1. 1. 1.]


In [22]:
# Numpy ni Tensor ga o'tkazish
a = np.array([1,2,3])
b = torch.from_numpy(a)
print("Numpy: " ,  a)
print("Tensor: " , b)

Numpy:  [1 2 3]
Tensor:  tensor([1, 2, 3])
